; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 128000
build_flags = 
	-DSERIAL_RX_BUFFER_SIZE=4096
	-DSERIAL_TX_BUFFER_SIZE=4096
	-DUSBMANUFACTURER="RGL"
	-DUSB_PRODUCT="BBL_Wifi-USB_BRIDGE"
